clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1 # CI does not need commit history
      recursive: true

pipeline:
  install:
    when:
      branch: main
      event: push
    image: node:18.6.0
    commands:
      - yarn install
  lint:
    when:
      branch: main
      event: push
    image: node:18.6.0
    commands:
      - yarn workspace sw run lint
